//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDirectiva.Presentacion.Resource.Base {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GenericResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenericResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GDirectiva.Presentacion.Resource.Base.GenericResource", typeof(GenericResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string BotonAgregar {
            get {
                return ResourceManager.GetString("BotonAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string BotonCerrar {
            get {
                return ResourceManager.GetString("BotonCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesión.
        /// </summary>
        public static string BotonCerrarSesion {
            get {
                return ResourceManager.GetString("BotonCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string BotonEliminar {
            get {
                return ResourceManager.GetString("BotonEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grabar.
        /// </summary>
        public static string BotonGrabar {
            get {
                return ResourceManager.GetString("BotonGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        public static string BotonLimpiar {
            get {
                return ResourceManager.GetString("BotonLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        public static string BotonModificar {
            get {
                return ResourceManager.GetString("BotonModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar.
        /// </summary>
        public static string BotonMostrar {
            get {
                return ResourceManager.GetString("BotonMostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string BotonRegistrar {
            get {
                return ResourceManager.GetString("BotonRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string BotonRegresar {
            get {
                return ResourceManager.GetString("BotonRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cronograma.
        /// </summary>
        public static string EtiquetaCalendario {
            get {
                return ResourceManager.GetString("EtiquetaCalendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivar.
        /// </summary>
        public static string EtiquetaDesactivar {
            get {
                return ResourceManager.GetString("EtiquetaDesactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string EtiquetaEditar {
            get {
                return ResourceManager.GetString("EtiquetaEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string EtiquetaEliminar {
            get {
                return ResourceManager.GetString("EtiquetaEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar actividades.
        /// </summary>
        public static string EtiquetaEliminarActividades {
            get {
                return ResourceManager.GetString("EtiquetaEliminarActividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado de la búsqueda.
        /// </summary>
        public static string EtiquetaResultadosBusqueda {
            get {
                return ResourceManager.GetString("EtiquetaResultadosBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --SELECCIONE--.
        /// </summary>
        public static string EtiquetaSeleccionar {
            get {
                return ResourceManager.GetString("EtiquetaSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innova Schools.
        /// </summary>
        public static string EtiquetaTituloSistema {
            get {
                return ResourceManager.GetString("EtiquetaTituloSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (TODOS).
        /// </summary>
        public static string EtiquetaTodos {
            get {
                return ResourceManager.GetString("EtiquetaTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string GridAcciones {
            get {
                return ResourceManager.GetString("GridAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles.
        /// </summary>
        public static string GridControles {
            get {
                return ResourceManager.GetString("GridControles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un texto..
        /// </summary>
        public static string MensajeDebeIngresarUnTexto {
            get {
                return ResourceManager.GetString("MensajeDebeIngresarUnTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se desactivó con éxito..
        /// </summary>
        public static string MensajeSeDesactivoConExito {
            get {
                return ResourceManager.GetString("MensajeSeDesactivoConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se eliminó con éxito..
        /// </summary>
        public static string MensajeSeEliminoConExito {
            get {
                return ResourceManager.GetString("MensajeSeEliminoConExito", resourceCulture);
            }
        }
    }
}
