//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDirectiva.Presentacion.Resource.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlanAsignaturaCronogramaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlanAsignaturaCronogramaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GDirectiva.Presentacion.Resource.General.PlanAsignaturaCronogramaResource", typeof(PlanAsignaturaCronogramaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignatura.
        /// </summary>
        public static string EtiquetaAsignatura {
            get {
                return ResourceManager.GetString("EtiquetaAsignatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docente.
        /// </summary>
        public static string EtiquetaDocente {
            get {
                return ResourceManager.GetString("EtiquetaDocente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Fin.
        /// </summary>
        public static string EtiquetaFechaFin {
            get {
                return ResourceManager.GetString("EtiquetaFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicio.
        /// </summary>
        public static string EtiquetaFechaInicio {
            get {
                return ResourceManager.GetString("EtiquetaFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta.
        /// </summary>
        public static string EtiquetaMetas {
            get {
                return ResourceManager.GetString("EtiquetaMetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metodologías.
        /// </summary>
        public static string EtiquetaMetodologias {
            get {
                return ResourceManager.GetString("EtiquetaMetodologias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad.
        /// </summary>
        public static string EtiquetaNombreActividad {
            get {
                return ResourceManager.GetString("EtiquetaNombreActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo Académico.
        /// </summary>
        public static string EtiquetaPeriodoAcademico {
            get {
                return ResourceManager.GetString("EtiquetaPeriodoAcademico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Área.
        /// </summary>
        public static string EtiquetaPlanArea {
            get {
                return ResourceManager.GetString("EtiquetaPlanArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentaje.
        /// </summary>
        public static string EtiquetaPorcentaje {
            get {
                return ResourceManager.GetString("EtiquetaPorcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regla.
        /// </summary>
        public static string EtiquetaRegla {
            get {
                return ResourceManager.GetString("EtiquetaRegla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable.
        /// </summary>
        public static string EtiquetaResponsables {
            get {
                return ResourceManager.GetString("EtiquetaResponsables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado de la búsqueda.
        /// </summary>
        public static string EtiquetaResultadosBusqueda {
            get {
                return ResourceManager.GetString("EtiquetaResultadosBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar una regla..
        /// </summary>
        public static string EtiquetaSeleccionarUnaRegla {
            get {
                return ResourceManager.GetString("EtiquetaSeleccionarUnaRegla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario de Registro de Cronograma de Plan de Asignatura.
        /// </summary>
        public static string EtiquetaTituloFormulario {
            get {
                return ResourceManager.GetString("EtiquetaTituloFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario de Actividad.
        /// </summary>
        public static string EtiquetaTituloFormularioActividad {
            get {
                return ResourceManager.GetString("EtiquetaTituloFormularioActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Asignatura.
        /// </summary>
        public static string EtiquetaTituloPrincipal {
            get {
                return ResourceManager.GetString("EtiquetaTituloPrincipal", resourceCulture);
            }
        }
    }
}
