//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDirectiva.Presentacion.Resource.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlanAreaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlanAreaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GDirectiva.Presentacion.Resource.General.PlanAreaResource", typeof(PlanAreaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de extensión: Archivo Inválido, solo se acepta archivos de tipo Word..
        /// </summary>
        public static string ErrorDeExtension {
            get {
                return ResourceManager.GetString("ErrorDeExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área Curricular.
        /// </summary>
        public static string EtiquetaArea {
            get {
                return ResourceManager.GetString("EtiquetaArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criterios.
        /// </summary>
        public static string EtiquetaCriterios {
            get {
                return ResourceManager.GetString("EtiquetaCriterios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        public static string EtiquetaDocumento {
            get {
                return ResourceManager.GetString("EtiquetaDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string EtiquetaEstado {
            get {
                return ResourceManager.GetString("EtiquetaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grado.
        /// </summary>
        public static string EtiquetaGrado {
            get {
                return ResourceManager.GetString("EtiquetaGrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string EtiquetaNombre {
            get {
                return ResourceManager.GetString("EtiquetaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Plan Área.
        /// </summary>
        public static string EtiquetaNombrePlanArea {
            get {
                return ResourceManager.GetString("EtiquetaNombrePlanArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objetivos.
        /// </summary>
        public static string EtiquetaObjetivos {
            get {
                return ResourceManager.GetString("EtiquetaObjetivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo académico.
        /// </summary>
        public static string EtiquetaPeriodoAcademico {
            get {
                return ResourceManager.GetString("EtiquetaPeriodoAcademico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisitos.
        /// </summary>
        public static string EtiquetaRequisitos {
            get {
                return ResourceManager.GetString("EtiquetaRequisitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado de la búsqueda.
        /// </summary>
        public static string EtiquetaResultadosBusqueda {
            get {
                return ResourceManager.GetString("EtiquetaResultadosBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un archivo.
        /// </summary>
        public static string EtiquetaSeleccioneUnArchivo {
            get {
                return ResourceManager.GetString("EtiquetaSeleccioneUnArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario de Plan Área.
        /// </summary>
        public static string EtiquetaTituloFormulario {
            get {
                return ResourceManager.GetString("EtiquetaTituloFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de Área.
        /// </summary>
        public static string EtiquetaTituloPrincipal {
            get {
                return ResourceManager.GetString("EtiquetaTituloPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar el archivo Excel (.doc | .docx)..
        /// </summary>
        public static string MensajeDebeSeleccionarArchivoWord {
            get {
                return ResourceManager.GetString("MensajeDebeSeleccionarArchivoWord", resourceCulture);
            }
        }
    }
}
