//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDirectiva.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignatura
    {
        public Asignatura()
        {
            this.PlanAsignatura = new HashSet<PlanAsignatura>();
        }
    
        public int Id_Asignatura { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Id_Area { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<PlanAsignatura> PlanAsignatura { get; set; }
    }
}
