//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDirectiva.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_Asignatura
    {
        public GD_Asignatura()
        {
            this.GD_Empleado_Asignatura = new HashSet<GD_Empleado_Asignatura>();
            this.GD_Plan_Asignatura = new HashSet<GD_Plan_Asignatura>();
        }
    
        public int Id_Asignatura { get; set; }
        public string Curso { get; set; }
        public int GD_Area_Id_Area { get; set; }
    
        public virtual GD_Area GD_Area { get; set; }
        public virtual ICollection<GD_Empleado_Asignatura> GD_Empleado_Asignatura { get; set; }
        public virtual ICollection<GD_Plan_Asignatura> GD_Plan_Asignatura { get; set; }
    }
}
