//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDirectiva.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_Empleado_Asignatura
    {
        public int Id_Asignatura_Empleado { get; set; }
        public int GD_Asignatura_Id_Asignatura { get; set; }
        public int GRMS_Empleado_Id_Empleado { get; set; }
    
        public virtual GD_Asignatura GD_Asignatura { get; set; }
        public virtual GRMS_Empleado GRMS_Empleado { get; set; }
    }
}
