//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDirectiva.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_Observacion
    {
        public int Id_Observacion { get; set; }
        public string Observacion { get; set; }
        public string Tipo { get; set; }
        public int GD_Plan_Asignatura_Id_Plan_Asignatura { get; set; }
    
        public virtual GD_Plan_Asignatura GD_Plan_Asignatura { get; set; }
    }
}
