//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDirectiva.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_Plan_Asignatura_Actividades
    {
        public int Id_Actividad { get; set; }
        public string Actividad { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
        public Nullable<int> Porcentaje_Avance { get; set; }
        public string Estado { get; set; }
        public int GD_Plan_Asignatura_Id_Plan_Asignatura { get; set; }
        public int GRMS_Empleado_Id_Empleado { get; set; }
    
        public virtual GD_Plan_Asignatura GD_Plan_Asignatura { get; set; }
        public virtual GRMS_Empleado GRMS_Empleado { get; set; }
    }
}
