//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDirectiva.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_Plan_Asignatura
    {
        public GD_Plan_Asignatura()
        {
            this.GD_Observacion = new HashSet<GD_Observacion>();
            this.GD_Plan_Asignatura_Actividades = new HashSet<GD_Plan_Asignatura_Actividades>();
        }
    
        public int Id_Plan_Asignatura { get; set; }
        public string Meta { get; set; }
        public string Metodologia { get; set; }
        public string Documento { get; set; }
        public string Estado { get; set; }
        public int GD_Plan_Area_Id_Plan_Area { get; set; }
        public int GRMS_Empleado_Id_Empleado { get; set; }
        public int GD_Asignatura_Id_Asignatura { get; set; }
    
        public virtual GD_Asignatura GD_Asignatura { get; set; }
        public virtual ICollection<GD_Observacion> GD_Observacion { get; set; }
        public virtual GD_Plan_Area GD_Plan_Area { get; set; }
        public virtual ICollection<GD_Plan_Asignatura_Actividades> GD_Plan_Asignatura_Actividades { get; set; }
        public virtual GRMS_Empleado GRMS_Empleado { get; set; }
    }
}
