//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDirectiva.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_Plan_Area
    {
        public GD_Plan_Area()
        {
            this.GD_Plan_Asignatura = new HashSet<GD_Plan_Asignatura>();
        }
    
        public int Id_Plan_Area { get; set; }
        public string Nombre { get; set; }
        public string Objetivos { get; set; }
        public string Criterios { get; set; }
        public string Requisitos { get; set; }
        public string Estado { get; set; }
        public string Documento { get; set; }
        public int GD_Periodo_Academico_Id_Periodo { get; set; }
        public int GD_Area_Id_Area { get; set; }
        public int GD_Grado_Id_Grado { get; set; }
    
        public virtual GD_Area GD_Area { get; set; }
        public virtual GD_Grado GD_Grado { get; set; }
        public virtual GD_Periodo_Academico GD_Periodo_Academico { get; set; }
        public virtual ICollection<GD_Plan_Asignatura> GD_Plan_Asignatura { get; set; }
    }
}
