//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDirectiva.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRMS_Empleado
    {
        public GRMS_Empleado()
        {
            this.GD_Empleado_Asignatura = new HashSet<GD_Empleado_Asignatura>();
            this.GD_Plan_Asignatura = new HashSet<GD_Plan_Asignatura>();
            this.GD_Plan_Asignatura_Actividades = new HashSet<GD_Plan_Asignatura_Actividades>();
        }
    
        public int Id_Empleado { get; set; }
        public string Documento { get; set; }
        public string Ape_Paterno { get; set; }
        public string Ape_Materno { get; set; }
        public string Nombres { get; set; }
        public string Rol { get; set; }
        public string Area { get; set; }
        public string Correo { get; set; }
    
        public virtual ICollection<GD_Empleado_Asignatura> GD_Empleado_Asignatura { get; set; }
        public virtual ICollection<GD_Plan_Asignatura> GD_Plan_Asignatura { get; set; }
        public virtual ICollection<GD_Plan_Asignatura_Actividades> GD_Plan_Asignatura_Actividades { get; set; }
    }
}
