//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDirectiva.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanAsignaturaMeta
    {
        public int Id_PlanAsignaturaMeta { get; set; }
        public int Id_PlanAsignatura { get; set; }
        public string Meta { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual PlanAsignatura PlanAsignatura { get; set; }
    }
}
