//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDirectiva.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanProyectoPedagogico
    {
        public PlanProyectoPedagogico()
        {
            this.ActividadPlanProyectoPedagogico = new HashSet<ActividadPlanProyectoPedagogico>();
        }
    
        public int Id_ProyectoPedagogico { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Objetivos { get; set; }
        public string Estado { get; set; }
        public byte[] Documento { get; set; }
        public Nullable<int> Id_PlanEstudio { get; set; }
        public Nullable<int> Id_PeriodoAcademico { get; set; }
        public Nullable<int> Id_Area { get; set; }
        public Nullable<int> Id_Grado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual ICollection<ActividadPlanProyectoPedagogico> ActividadPlanProyectoPedagogico { get; set; }
        public virtual Area Area { get; set; }
        public virtual Grado Grado { get; set; }
        public virtual PeriodoAcademico PeriodoAcademico { get; set; }
        public virtual PlanEstudio PlanEstudio { get; set; }
    }
}
