//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDirectiva.Presentacion.Resource.Mensaje {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GDirectiva.Presentacion.Resource.Mensaje.MensajeResource", typeof(MensajeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario Válido.
        /// </summary>
        public static string ComentarioValido {
            get {
                return ResourceManager.GetString("ComentarioValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de activar el registro?.
        /// </summary>
        public static string ConfirmacionActivacion {
            get {
                return ResourceManager.GetString("ConfirmacionActivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de eliminar el registro?.
        /// </summary>
        public static string ConfirmacionEliminacion {
            get {
                return ResourceManager.GetString("ConfirmacionEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de grabar los cambios solicitados?.
        /// </summary>
        public static string ConfirmacionGuardar {
            get {
                return ResourceManager.GetString("ConfirmacionGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una fecha..
        /// </summary>
        public static string DebeSeleccionarFecha {
            get {
                return ResourceManager.GetString("DebeSeleccionarFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar al menos un registro..
        /// </summary>
        public static string DebeSeleccionarRegistro {
            get {
                return ResourceManager.GetString("DebeSeleccionarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar sólo un registro..
        /// </summary>
        public static string DebeSeleccionarUnRegistro {
            get {
                return ResourceManager.GetString("DebeSeleccionarUnRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al grabar el registro..
        /// </summary>
        public static string ErroralGrabar {
            get {
                return ResourceManager.GetString("ErroralGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View model no definido..
        /// </summary>
        public static string ErrorCargarViewModel {
            get {
                return ResourceManager.GetString("ErrorCargarViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado. Inténtelo nuevamente.
        /// </summary>
        public static string EtiquetaErrorRegistro {
            get {
                return ResourceManager.GetString("EtiquetaErrorRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario estará activo hasta.
        /// </summary>
        public static string EtiquetaMensajeDesactivar {
            get {
                return ResourceManager.GetString("EtiquetaMensajeDesactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ejecuto ningun proceso..
        /// </summary>
        public static string EtiquetaNoEjecutoNingunProceso {
            get {
                return ResourceManager.GetString("EtiquetaNoEjecutoNingunProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de Demanda ya existe.
        /// </summary>
        public static string ExistenciaCodigoDemanda {
            get {
                return ResourceManager.GetString("ExistenciaCodigoDemanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de depósito distinto..
        /// </summary>
        public static string FechaRegistroDistinta {
            get {
                return ResourceManager.GetString("FechaRegistroDistinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe de pago distinto..
        /// </summary>
        public static string ImportePagoDistinta {
            get {
                return ResourceManager.GetString("ImportePagoDistinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar al menos un filtro de búsqueda..
        /// </summary>
        public static string InformacionIngresarFiltro {
            get {
                return ResourceManager.GetString("InformacionIngresarFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información mostrada corresponde a la.
        /// </summary>
        public static string InformacionPreFiltro {
            get {
                return ResourceManager.GetString("InformacionPreFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud no ha podido ser procesada. Comuníquese con el Administrador del Sistema..
        /// </summary>
        public static string MensajeException {
            get {
                return ResourceManager.GetString("MensajeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña autogenerada es:.
        /// </summary>
        public static string MensajeLaContraseniaAutogeneradaEs {
            get {
                return ResourceManager.GetString("MensajeLaContraseniaAutogeneradaEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los registros seleccionados no coinciden:.
        /// </summary>
        public static string RegistrosNoCoinciden {
            get {
                return ResourceManager.GetString("RegistrosNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se activó el registro con éxito..
        /// </summary>
        public static string SeActivoRegistro {
            get {
                return ResourceManager.GetString("SeActivoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se anuló registro con éxito..
        /// </summary>
        public static string SeAnuloRegistro {
            get {
                return ResourceManager.GetString("SeAnuloRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se eliminó el registro con éxito..
        /// </summary>
        public static string SeEliminoRegistro {
            get {
                return ResourceManager.GetString("SeEliminoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se guardó la información con éxito..
        /// </summary>
        public static string SeGuardoInformacionExito {
            get {
                return ResourceManager.GetString("SeGuardoInformacionExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al menos un parámetro de filtro correcto.
        /// </summary>
        public static string SeleccioneFiltro {
            get {
                return ResourceManager.GetString("SeleccioneFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se cargaron.
        /// </summary>
        public static string Texto1 {
            get {
                return ResourceManager.GetString("Texto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registros con éxito y.
        /// </summary>
        public static string Texto2 {
            get {
                return ResourceManager.GetString("Texto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sin éxito..
        /// </summary>
        public static string Texto3 {
            get {
                return ResourceManager.GetString("Texto3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor confirme la eliminación de los registros seleccionados..
        /// </summary>
        public static string TextoEliminacion {
            get {
                return ResourceManager.GetString("TextoEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor confirme la activación del registro..
        /// </summary>
        public static string TextoReactivacion {
            get {
                return ResourceManager.GetString("TextoReactivacion", resourceCulture);
            }
        }
    }
}
